// client/components/HeroSection.tsx
export default function HeroSection() {
  return (
    <div className="relative w-full mb-8">
      {/* Hero Image Container */}
      <div className="relative h-80 md:h-96 rounded-2xl overflow-hidden bg-gradient-to-r from-blue-400 to-purple-500">
        {/* Car Image */}
        <img
          src="https://api.builder.io/api/v1/image/assets/TEMP/4a0757a9eca2b54e714b83059a30c7b4c4969702?width=1936"
          alt="Airdrop Festival Car"
          className="w-full h-full object-cover"
        />

        {/* Overlay Content */}
        <div className="absolute inset-0 bg-black/20" />
        <div className="absolute bottom-0 left-0 right-0 p-8 text-white">
          <div className="max-w-4xl mx-4 text-left">
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4 leading-tight">
              Airdrop 感謝祭
            </h1>
            <p className="text-base md:text-lg text-white/90">
              發送 Airdrop & Quiz 獲得抽獎機會
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// vue-version/src/components/HeroSection.vue
<template>
  <div class="relative w-full mb-8">
    <div class="relative h-80 md:h-96 rounded-2xl overflow-hidden bg-gradient-to-r from-blue-400 to-purple-500">
      <img 
        src="https://api.builder.io/api/v1/image/assets/TEMP/4a0757a9eca2b54e714b83059a30c7b4c4969702?width=1936"
        alt="Airdrop Festival Car"
        class="w-full h-full object-cover"
      />
      
      <div class="absolute inset-0 bg-black/20" />
      <div class="absolute bottom-0 left-0 right-0 p-8 text-white">
        <div class="max-w-4xl mx-4 text-left">
          <h1 class="text-3xl md:text-4xl lg:text-5xl font-bold mb-4 leading-tight">
            Airdrop 感謝祭
          </h1>
          <p class="text-base md:text-lg text-white/90">
            發送 Airdrop & Quiz 獲得抽獎機會
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Hero section 組件邏輯
</script>
